# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'playersData.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(583, 747)
        MainWindow.setStyleSheet("QMainWindow {\n"
"   color:white;\n"
"}")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab1)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableView = QtWidgets.QTableView(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        self.tableView.setSizePolicy(sizePolicy)
        self.tableView.setAcceptDrops(False)
        self.tableView.setStyleSheet("")
        self.tableView.setFrameShape(QtWidgets.QFrame.Box)
        self.tableView.setAutoScroll(True)
        self.tableView.setSortingEnabled(True)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_3.addWidget(self.tableView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setSpacing(6)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lName_27 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_27.sizePolicy().hasHeightForWidth())
        self.lName_27.setSizePolicy(sizePolicy)
        self.lName_27.setObjectName("lName_27")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lName_27)
        self.lName_28 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_28.sizePolicy().hasHeightForWidth())
        self.lName_28.setSizePolicy(sizePolicy)
        self.lName_28.setObjectName("lName_28")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lName_28)
        self.lineName = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineName.sizePolicy().hasHeightForWidth())
        self.lineName.setSizePolicy(sizePolicy)
        self.lineName.setMinimumSize(QtCore.QSize(160, 0))
        self.lineName.setObjectName("lineName")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineName)
        self.lineTeam = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineTeam.sizePolicy().hasHeightForWidth())
        self.lineTeam.setSizePolicy(sizePolicy)
        self.lineTeam.setObjectName("lineTeam")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineTeam)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_2.setSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lName = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName.sizePolicy().hasHeightForWidth())
        self.lName.setSizePolicy(sizePolicy)
        self.lName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lName.setObjectName("lName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lName)
        self.lineAge = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineAge.sizePolicy().hasHeightForWidth())
        self.lineAge.setSizePolicy(sizePolicy)
        self.lineAge.setMinimumSize(QtCore.QSize(50, 20))
        self.lineAge.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineAge.setBaseSize(QtCore.QSize(50, 20))
        self.lineAge.setObjectName("lineAge")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineAge)
        self.lName_2 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_2.sizePolicy().hasHeightForWidth())
        self.lName_2.setSizePolicy(sizePolicy)
        self.lName_2.setObjectName("lName_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lName_2)
        self.lineHeight = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineHeight.sizePolicy().hasHeightForWidth())
        self.lineHeight.setSizePolicy(sizePolicy)
        self.lineHeight.setMinimumSize(QtCore.QSize(50, 20))
        self.lineHeight.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineHeight.setBaseSize(QtCore.QSize(50, 20))
        self.lineHeight.setObjectName("lineHeight")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineHeight)
        self.lName_3 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_3.sizePolicy().hasHeightForWidth())
        self.lName_3.setSizePolicy(sizePolicy)
        self.lName_3.setObjectName("lName_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lName_3)
        self.lineWorkingFoot = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineWorkingFoot.sizePolicy().hasHeightForWidth())
        self.lineWorkingFoot.setSizePolicy(sizePolicy)
        self.lineWorkingFoot.setMinimumSize(QtCore.QSize(50, 20))
        self.lineWorkingFoot.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineWorkingFoot.setBaseSize(QtCore.QSize(50, 20))
        self.lineWorkingFoot.setObjectName("lineWorkingFoot")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineWorkingFoot)
        self.lName_4 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_4.sizePolicy().hasHeightForWidth())
        self.lName_4.setSizePolicy(sizePolicy)
        self.lName_4.setObjectName("lName_4")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lName_4)
        self.lineAcceleration = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineAcceleration.sizePolicy().hasHeightForWidth())
        self.lineAcceleration.setSizePolicy(sizePolicy)
        self.lineAcceleration.setMinimumSize(QtCore.QSize(50, 20))
        self.lineAcceleration.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineAcceleration.setBaseSize(QtCore.QSize(50, 20))
        self.lineAcceleration.setObjectName("lineAcceleration")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineAcceleration)
        self.lName_5 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_5.sizePolicy().hasHeightForWidth())
        self.lName_5.setSizePolicy(sizePolicy)
        self.lName_5.setObjectName("lName_5")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lName_5)
        self.lineJerkSpeed = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineJerkSpeed.sizePolicy().hasHeightForWidth())
        self.lineJerkSpeed.setSizePolicy(sizePolicy)
        self.lineJerkSpeed.setMinimumSize(QtCore.QSize(50, 20))
        self.lineJerkSpeed.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineJerkSpeed.setBaseSize(QtCore.QSize(50, 20))
        self.lineJerkSpeed.setObjectName("lineJerkSpeed")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineJerkSpeed)
        self.lName_16 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_16.sizePolicy().hasHeightForWidth())
        self.lName_16.setSizePolicy(sizePolicy)
        self.lName_16.setObjectName("lName_16")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lName_16)
        self.linePositionSelection = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linePositionSelection.sizePolicy().hasHeightForWidth())
        self.linePositionSelection.setSizePolicy(sizePolicy)
        self.linePositionSelection.setMinimumSize(QtCore.QSize(50, 20))
        self.linePositionSelection.setMaximumSize(QtCore.QSize(50, 16777215))
        self.linePositionSelection.setBaseSize(QtCore.QSize(50, 20))
        self.linePositionSelection.setObjectName("linePositionSelection")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.linePositionSelection)
        self.lName_17 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_17.sizePolicy().hasHeightForWidth())
        self.lName_17.setSizePolicy(sizePolicy)
        self.lName_17.setObjectName("lName_17")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lName_17)
        self.lineCompletion = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineCompletion.sizePolicy().hasHeightForWidth())
        self.lineCompletion.setSizePolicy(sizePolicy)
        self.lineCompletion.setMinimumSize(QtCore.QSize(50, 20))
        self.lineCompletion.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineCompletion.setBaseSize(QtCore.QSize(50, 20))
        self.lineCompletion.setObjectName("lineCompletion")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineCompletion)
        self.lName_18 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_18.sizePolicy().hasHeightForWidth())
        self.lName_18.setSizePolicy(sizePolicy)
        self.lName_18.setObjectName("lName_18")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lName_18)
        self.lineImpactStrength = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineImpactStrength.sizePolicy().hasHeightForWidth())
        self.lineImpactStrength.setSizePolicy(sizePolicy)
        self.lineImpactStrength.setMinimumSize(QtCore.QSize(50, 20))
        self.lineImpactStrength.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineImpactStrength.setBaseSize(QtCore.QSize(50, 20))
        self.lineImpactStrength.setObjectName("lineImpactStrength")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineImpactStrength)
        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineBallSpin = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineBallSpin.sizePolicy().hasHeightForWidth())
        self.lineBallSpin.setSizePolicy(sizePolicy)
        self.lineBallSpin.setMinimumSize(QtCore.QSize(50, 20))
        self.lineBallSpin.setMaximumSize(QtCore.QSize(50, 20))
        self.lineBallSpin.setBaseSize(QtCore.QSize(50, 20))
        self.lineBallSpin.setObjectName("lineBallSpin")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineBallSpin)
        self.label_2 = QtWidgets.QLabel(self.tab1)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineDexterity = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineDexterity.sizePolicy().hasHeightForWidth())
        self.lineDexterity.setSizePolicy(sizePolicy)
        self.lineDexterity.setMinimumSize(QtCore.QSize(50, 20))
        self.lineDexterity.setMaximumSize(QtCore.QSize(50, 20))
        self.lineDexterity.setBaseSize(QtCore.QSize(50, 20))
        self.lineDexterity.setObjectName("lineDexterity")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineDexterity)
        self.label_3 = QtWidgets.QLabel(self.tab1)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineBalance = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineBalance.sizePolicy().hasHeightForWidth())
        self.lineBalance.setSizePolicy(sizePolicy)
        self.lineBalance.setMinimumSize(QtCore.QSize(50, 20))
        self.lineBalance.setMaximumSize(QtCore.QSize(50, 20))
        self.lineBalance.setBaseSize(QtCore.QSize(50, 20))
        self.lineBalance.setObjectName("lineBalance")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineBalance)
        self.label_4 = QtWidgets.QLabel(self.tab1)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineReaction = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineReaction.sizePolicy().hasHeightForWidth())
        self.lineReaction.setSizePolicy(sizePolicy)
        self.lineReaction.setMinimumSize(QtCore.QSize(50, 20))
        self.lineReaction.setMaximumSize(QtCore.QSize(50, 20))
        self.lineReaction.setBaseSize(QtCore.QSize(50, 20))
        self.lineReaction.setObjectName("lineReaction")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineReaction)
        self.label_5 = QtWidgets.QLabel(self.tab1)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineBallControl = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineBallControl.sizePolicy().hasHeightForWidth())
        self.lineBallControl.setSizePolicy(sizePolicy)
        self.lineBallControl.setMinimumSize(QtCore.QSize(50, 20))
        self.lineBallControl.setMaximumSize(QtCore.QSize(50, 20))
        self.lineBallControl.setBaseSize(QtCore.QSize(50, 20))
        self.lineBallControl.setObjectName("lineBallControl")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lineBallControl)
        self.label_6 = QtWidgets.QLabel(self.tab1)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineDribbling = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineDribbling.sizePolicy().hasHeightForWidth())
        self.lineDribbling.setSizePolicy(sizePolicy)
        self.lineDribbling.setMinimumSize(QtCore.QSize(50, 20))
        self.lineDribbling.setMaximumSize(QtCore.QSize(50, 20))
        self.lineDribbling.setBaseSize(QtCore.QSize(50, 20))
        self.lineDribbling.setObjectName("lineDribbling")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.lineDribbling)
        self.label_7 = QtWidgets.QLabel(self.tab1)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineSelfControl = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineSelfControl.sizePolicy().hasHeightForWidth())
        self.lineSelfControl.setSizePolicy(sizePolicy)
        self.lineSelfControl.setMinimumSize(QtCore.QSize(50, 20))
        self.lineSelfControl.setMaximumSize(QtCore.QSize(50, 20))
        self.lineSelfControl.setBaseSize(QtCore.QSize(50, 20))
        self.lineSelfControl.setObjectName("lineSelfControl")
        self.formLayout_2.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.lineSelfControl)
        self.label_8 = QtWidgets.QLabel(self.tab1)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.lineIntercepts = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineIntercepts.sizePolicy().hasHeightForWidth())
        self.lineIntercepts.setSizePolicy(sizePolicy)
        self.lineIntercepts.setMinimumSize(QtCore.QSize(50, 20))
        self.lineIntercepts.setMaximumSize(QtCore.QSize(50, 20))
        self.lineIntercepts.setBaseSize(QtCore.QSize(50, 20))
        self.lineIntercepts.setObjectName("lineIntercepts")
        self.formLayout_2.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.lineIntercepts)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lName_19 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_19.sizePolicy().hasHeightForWidth())
        self.lName_19.setSizePolicy(sizePolicy)
        self.lName_19.setObjectName("lName_19")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lName_19)
        self.lineLongShots = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineLongShots.sizePolicy().hasHeightForWidth())
        self.lineLongShots.setSizePolicy(sizePolicy)
        self.lineLongShots.setMinimumSize(QtCore.QSize(50, 20))
        self.lineLongShots.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineLongShots.setBaseSize(QtCore.QSize(50, 20))
        self.lineLongShots.setObjectName("lineLongShots")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineLongShots)
        self.lName_20 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_20.sizePolicy().hasHeightForWidth())
        self.lName_20.setSizePolicy(sizePolicy)
        self.lName_20.setObjectName("lName_20")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lName_20)
        self.lineHorsebackRiding = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineHorsebackRiding.sizePolicy().hasHeightForWidth())
        self.lineHorsebackRiding.setSizePolicy(sizePolicy)
        self.lineHorsebackRiding.setMinimumSize(QtCore.QSize(50, 20))
        self.lineHorsebackRiding.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineHorsebackRiding.setBaseSize(QtCore.QSize(50, 20))
        self.lineHorsebackRiding.setObjectName("lineHorsebackRiding")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineHorsebackRiding)
        self.lName_21 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_21.sizePolicy().hasHeightForWidth())
        self.lName_21.setSizePolicy(sizePolicy)
        self.lName_21.setObjectName("lName_21")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lName_21)
        self.linePenalty = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.linePenalty.sizePolicy().hasHeightForWidth())
        self.linePenalty.setSizePolicy(sizePolicy)
        self.linePenalty.setMinimumSize(QtCore.QSize(50, 20))
        self.linePenalty.setMaximumSize(QtCore.QSize(50, 16777215))
        self.linePenalty.setBaseSize(QtCore.QSize(50, 20))
        self.linePenalty.setObjectName("linePenalty")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.linePenalty)
        self.lName_22 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_22.sizePolicy().hasHeightForWidth())
        self.lName_22.setSizePolicy(sizePolicy)
        self.lName_22.setObjectName("lName_22")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lName_22)
        self.lineFieldVision = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineFieldVision.sizePolicy().hasHeightForWidth())
        self.lineFieldVision.setSizePolicy(sizePolicy)
        self.lineFieldVision.setMinimumSize(QtCore.QSize(50, 20))
        self.lineFieldVision.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineFieldVision.setBaseSize(QtCore.QSize(50, 20))
        self.lineFieldVision.setObjectName("lineFieldVision")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineFieldVision)
        self.lName_23 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_23.sizePolicy().hasHeightForWidth())
        self.lName_23.setSizePolicy(sizePolicy)
        self.lName_23.setObjectName("lName_23")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lName_23)
        self.lineAwnings = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineAwnings.sizePolicy().hasHeightForWidth())
        self.lineAwnings.setSizePolicy(sizePolicy)
        self.lineAwnings.setMinimumSize(QtCore.QSize(50, 20))
        self.lineAwnings.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineAwnings.setBaseSize(QtCore.QSize(50, 20))
        self.lineAwnings.setObjectName("lineAwnings")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineAwnings)
        self.lName_24 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_24.sizePolicy().hasHeightForWidth())
        self.lName_24.setSizePolicy(sizePolicy)
        self.lName_24.setObjectName("lName_24")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lName_24)
        self.lineStandards = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineStandards.sizePolicy().hasHeightForWidth())
        self.lineStandards.setSizePolicy(sizePolicy)
        self.lineStandards.setMinimumSize(QtCore.QSize(50, 20))
        self.lineStandards.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineStandards.setBaseSize(QtCore.QSize(50, 20))
        self.lineStandards.setObjectName("lineStandards")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lineStandards)
        self.lName_25 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_25.sizePolicy().hasHeightForWidth())
        self.lName_25.setSizePolicy(sizePolicy)
        self.lName_25.setObjectName("lName_25")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lName_25)
        self.lineShortPass = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineShortPass.sizePolicy().hasHeightForWidth())
        self.lineShortPass.setSizePolicy(sizePolicy)
        self.lineShortPass.setMinimumSize(QtCore.QSize(50, 20))
        self.lineShortPass.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineShortPass.setBaseSize(QtCore.QSize(50, 20))
        self.lineShortPass.setObjectName("lineShortPass")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineShortPass)
        self.lName_26 = QtWidgets.QLabel(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lName_26.sizePolicy().hasHeightForWidth())
        self.lName_26.setSizePolicy(sizePolicy)
        self.lName_26.setObjectName("lName_26")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lName_26)
        self.lineLongPass = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineLongPass.sizePolicy().hasHeightForWidth())
        self.lineLongPass.setSizePolicy(sizePolicy)
        self.lineLongPass.setMinimumSize(QtCore.QSize(50, 20))
        self.lineLongPass.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineLongPass.setBaseSize(QtCore.QSize(50, 20))
        self.lineLongPass.setObjectName("lineLongPass")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lineLongPass)
        self.label_11 = QtWidgets.QLabel(self.tab1)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineHeadGame = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineHeadGame.sizePolicy().hasHeightForWidth())
        self.lineHeadGame.setSizePolicy(sizePolicy)
        self.lineHeadGame.setMinimumSize(QtCore.QSize(50, 20))
        self.lineHeadGame.setMaximumSize(QtCore.QSize(50, 20))
        self.lineHeadGame.setBaseSize(QtCore.QSize(50, 20))
        self.lineHeadGame.setObjectName("lineHeadGame")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lineHeadGame)
        self.label_12 = QtWidgets.QLabel(self.tab1)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineCustody = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineCustody.sizePolicy().hasHeightForWidth())
        self.lineCustody.setSizePolicy(sizePolicy)
        self.lineCustody.setMinimumSize(QtCore.QSize(50, 20))
        self.lineCustody.setMaximumSize(QtCore.QSize(50, 20))
        self.lineCustody.setBaseSize(QtCore.QSize(50, 20))
        self.lineCustody.setObjectName("lineCustody")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lineCustody)
        self.label_16 = QtWidgets.QLabel(self.tab1)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.lineBallSelection = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineBallSelection.sizePolicy().hasHeightForWidth())
        self.lineBallSelection.setSizePolicy(sizePolicy)
        self.lineBallSelection.setMinimumSize(QtCore.QSize(50, 20))
        self.lineBallSelection.setMaximumSize(QtCore.QSize(50, 20))
        self.lineBallSelection.setBaseSize(QtCore.QSize(50, 20))
        self.lineBallSelection.setObjectName("lineBallSelection")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lineBallSelection)
        self.label_9 = QtWidgets.QLabel(self.tab1)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.lineTackles = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineTackles.sizePolicy().hasHeightForWidth())
        self.lineTackles.setSizePolicy(sizePolicy)
        self.lineTackles.setMinimumSize(QtCore.QSize(50, 20))
        self.lineTackles.setMaximumSize(QtCore.QSize(50, 20))
        self.lineTackles.setBaseSize(QtCore.QSize(50, 20))
        self.lineTackles.setObjectName("lineTackles")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.lineTackles)
        self.label_13 = QtWidgets.QLabel(self.tab1)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineJumpingAbility = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineJumpingAbility.sizePolicy().hasHeightForWidth())
        self.lineJumpingAbility.setSizePolicy(sizePolicy)
        self.lineJumpingAbility.setMinimumSize(QtCore.QSize(50, 20))
        self.lineJumpingAbility.setMaximumSize(QtCore.QSize(50, 20))
        self.lineJumpingAbility.setBaseSize(QtCore.QSize(50, 20))
        self.lineJumpingAbility.setObjectName("lineJumpingAbility")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.lineJumpingAbility)
        self.label_14 = QtWidgets.QLabel(self.tab1)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEndurance = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEndurance.sizePolicy().hasHeightForWidth())
        self.lineEndurance.setSizePolicy(sizePolicy)
        self.lineEndurance.setMinimumSize(QtCore.QSize(50, 20))
        self.lineEndurance.setMaximumSize(QtCore.QSize(50, 20))
        self.lineEndurance.setBaseSize(QtCore.QSize(50, 20))
        self.lineEndurance.setObjectName("lineEndurance")
        self.formLayout.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.lineEndurance)
        self.label_15 = QtWidgets.QLabel(self.tab1)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.lineForce = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineForce.sizePolicy().hasHeightForWidth())
        self.lineForce.setSizePolicy(sizePolicy)
        self.lineForce.setMinimumSize(QtCore.QSize(50, 20))
        self.lineForce.setMaximumSize(QtCore.QSize(50, 20))
        self.lineForce.setBaseSize(QtCore.QSize(50, 20))
        self.lineForce.setObjectName("lineForce")
        self.formLayout.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.lineForce)
        self.label_10 = QtWidgets.QLabel(self.tab1)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.lineAggressiveness = QtWidgets.QLineEdit(self.tab1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineAggressiveness.sizePolicy().hasHeightForWidth())
        self.lineAggressiveness.setSizePolicy(sizePolicy)
        self.lineAggressiveness.setMinimumSize(QtCore.QSize(50, 20))
        self.lineAggressiveness.setMaximumSize(QtCore.QSize(50, 20))
        self.lineAggressiveness.setBaseSize(QtCore.QSize(50, 20))
        self.lineAggressiveness.setObjectName("lineAggressiveness")
        self.formLayout.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.lineAggressiveness)
        self.horizontalLayout_2.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pSave = QtWidgets.QPushButton(self.tab1)
        self.pSave.setObjectName("pSave")
        self.verticalLayout.addWidget(self.pSave)
        self.pStart = QtWidgets.QPushButton(self.tab1)
        self.pStart.setObjectName("pStart")
        self.verticalLayout.addWidget(self.pStart)
        self.pPrevious = QtWidgets.QPushButton(self.tab1)
        self.pPrevious.setObjectName("pPrevious")
        self.verticalLayout.addWidget(self.pPrevious)
        self.pNext = QtWidgets.QPushButton(self.tab1)
        self.pNext.setObjectName("pNext")
        self.verticalLayout.addWidget(self.pNext)
        self.pLast = QtWidgets.QPushButton(self.tab1)
        self.pLast.setObjectName("pLast")
        self.verticalLayout.addWidget(self.pLast)
        self.pExit = QtWidgets.QPushButton(self.tab1)
        self.pExit.setObjectName("pExit")
        self.verticalLayout.addWidget(self.pExit)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.tab1, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.dbFirst = QtWidgets.QAction(MainWindow)
        self.dbFirst.setObjectName("dbFirst")
        self.dbPrev = QtWidgets.QAction(MainWindow)
        self.dbPrev.setObjectName("dbPrev")
        self.dbNext = QtWidgets.QAction(MainWindow)
        self.dbNext.setObjectName("dbNext")
        self.dbLast = QtWidgets.QAction(MainWindow)
        self.dbLast.setObjectName("dbLast")
        self.dbSave = QtWidgets.QAction(MainWindow)
        self.dbSave.setObjectName("dbSave")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Футбольный Редактор"))
        self.lName_27.setText(_translate("MainWindow", "Player"))
        self.lName_28.setText(_translate("MainWindow", "Team"))
        self.lName.setText(_translate("MainWindow", "Age"))
        self.lName_2.setText(_translate("MainWindow", "Height"))
        self.lName_3.setText(_translate("MainWindow", "WorkingFoot"))
        self.lName_4.setText(_translate("MainWindow", "Acceleration"))
        self.lName_5.setText(_translate("MainWindow", "JerkSpeed"))
        self.lName_16.setText(_translate("MainWindow", "PositionSelection"))
        self.lName_17.setText(_translate("MainWindow", "Completion"))
        self.lName_18.setText(_translate("MainWindow", "ImpactStrength"))
        self.label.setText(_translate("MainWindow", "BallSpin"))
        self.label_2.setText(_translate("MainWindow", "Dexterity"))
        self.label_3.setText(_translate("MainWindow", "Balance"))
        self.label_4.setText(_translate("MainWindow", "Reaction"))
        self.label_5.setText(_translate("MainWindow", "BallControl"))
        self.label_6.setText(_translate("MainWindow", "Dribbling"))
        self.label_7.setText(_translate("MainWindow", "SelfControl"))
        self.label_8.setText(_translate("MainWindow", "Intercepts"))
        self.lName_19.setText(_translate("MainWindow", "LongShots"))
        self.lName_20.setText(_translate("MainWindow", "HorsebackRiding"))
        self.lName_21.setText(_translate("MainWindow", "Penalty"))
        self.lName_22.setText(_translate("MainWindow", "FieldVision"))
        self.lName_23.setText(_translate("MainWindow", "Awnings"))
        self.lName_24.setText(_translate("MainWindow", "Standards"))
        self.lName_25.setText(_translate("MainWindow", "ShortPass"))
        self.lName_26.setText(_translate("MainWindow", "LongPass"))
        self.label_11.setText(_translate("MainWindow", "HeadGame"))
        self.label_12.setText(_translate("MainWindow", "Custody"))
        self.label_16.setText(_translate("MainWindow", "BallSelection"))
        self.label_9.setText(_translate("MainWindow", "Tackles"))
        self.label_13.setText(_translate("MainWindow", "JumpingAbility"))
        self.label_14.setText(_translate("MainWindow", "Endurance"))
        self.label_15.setText(_translate("MainWindow", "Force"))
        self.label_10.setText(_translate("MainWindow", "Aggressiveness"))
        self.pSave.setText(_translate("MainWindow", "Сохранить изменения"))
        self.pStart.setText(_translate("MainWindow", "В начало"))
        self.pPrevious.setText(_translate("MainWindow", "Предыдущий"))
        self.pNext.setText(_translate("MainWindow", "Следующий"))
        self.pLast.setText(_translate("MainWindow", "В конец"))
        self.pExit.setText(_translate("MainWindow", "Выход в Главное меню"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("MainWindow", "Редактор"))
        self.dbFirst.setText(_translate("MainWindow", "<<"))
        self.dbFirst.setToolTip(_translate("MainWindow", "Первая запись"))
        self.dbPrev.setText(_translate("MainWindow", "<"))
        self.dbPrev.setToolTip(_translate("MainWindow", "Предыдущий"))
        self.dbNext.setText(_translate("MainWindow", ">"))
        self.dbNext.setToolTip(_translate("MainWindow", "Следующий"))
        self.dbLast.setText(_translate("MainWindow", ">>"))
        self.dbLast.setToolTip(_translate("MainWindow", "Последний"))
        self.dbSave.setText(_translate("MainWindow", "Save"))
